name: Frontend CI/CD

on:
  push:
    branches:
      - develop
    paths:
      - 'frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2   # Checks out repository code at the commit being built.
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2 # make sure AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY secrets are set in repository settings.
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Sync frontend to S3 bucket
        run: |
          aws s3 sync frontend s3://static-frontend-uihdfs87ytf764gh --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"